pipeline:

  my-build:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t hello-peeps .
    when:
      branch: master
      event: push

  pr-builder:
    privileged: true
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t hello-peeps .
    when:
      event: pull_request

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="sulthan_ahmed" -p=${DOCKER_PASSWORD} quay.io
      - docker tag hello-peeps quay.io/ukhomeofficedigital/hello-peeps:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/hello-peeps:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  image_to_artifactory:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="regt-build-bot" -p=${DOCKER_ARTIFACTORY_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker tag hello-peeps docker.digital.homeoffice.gov.uk/ukhomeofficedigital/hello-peeps:${DRONE_COMMIT_SHA}
      - docker push docker.digital.homeoffice.gov.uk/ukhomeofficedigital/hello-peeps:${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy-to-preprod:
    image: busybox
    commands:
      - /bin/echo hello preprod ${NAME}
    when:
      environment: preprod
      event: deployment

services:
  dind:
    image: docker:1.11-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
